<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_BuyerVol3</name>
   <tag></tag>
   <elementGuidId>da1bb602-c024-49b9-8a8f-e375b92dc170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sc-crXcEl.styled__Td-sc-wb8gs0-1.ibdGcM.GqUtV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>62253de9-c2c4-479d-b438-e927ce9dfb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>fe201379-2e9a-41d3-a31a-10e26bd32d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9070131e-75c2-436c-a8c8-4278d5f0af6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>b9f9178c-ccea-4cb9-81c3-81c14ea7ade9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>5543fc6b-6eb5-404e-9544-4be7c43e016b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>padding</name>
      <type>Main</type>
      <value>6px</value>
      <webElementGuid>dca36e9f-d8e9-48b1-b67e-4169f339b8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>family</name>
      <type>Main</type>
      <value>regular</value>
      <webElementGuid>41b3a33e-bda4-4c2f-9724-63073285045d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>a62df9df-cc4d-4884-8284-29ca77e8edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-crXcEl styled__Td-sc-wb8gs0-1 ibdGcM GqUtV</value>
      <webElementGuid>6d1f7c1c-9a7e-4c98-ba5c-5482cda11510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minwidth</name>
      <type>Main</type>
      <value>40px</value>
      <webElementGuid>d2ad5e35-5796-47ef-9b4d-50b4aee386b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 M</value>
      <webElementGuid>7a2f17f5-5a30-40e6-86cb-a5eb601ba6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-BROKER_SUMMARY&quot;)/div[@class=&quot;ant-table-wrapper sc-ehMyHa styled__TableListTransaction-sc-wb8gs0-14 eThjKr kcEcRq&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-ping-right ant-table-fixed-header ant-table-scroll-horizontal&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-body&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/p[@class=&quot;sc-crXcEl styled__Td-sc-wb8gs0-1 ibdGcM GqUtV&quot;]</value>
      <webElementGuid>e16be33f-d82f-4857-b787-58fe5ab45eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@type='up']</value>
      <webElementGuid>12960bc9-03e9-455a-96d4-5d5d658f4906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-BROKER_SUMMARY']/div[2]/div/div/div/div/div[2]/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>edaf9f06-d71c-4373-bd3d-6ee5dcb672a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net'])[1]/following::p[51]</value>
      <webElementGuid>15cc8ffa-b252-46d6-9c8b-b6e3188ac897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular'])[1]/following::p[51]</value>
      <webElementGuid>f75420ad-c48f-4d28-98bd-490d4889bb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATO'])[1]/preceding::p[89]</value>
      <webElementGuid>60400662-fcc5-4909-8582-08d6955db8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surya Permata Andalan Tbk.'])[1]/preceding::p[89]</value>
      <webElementGuid>38570312-28e7-4b4c-90cf-ede25076433f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2 M']/parent::*</value>
      <webElementGuid>aeff1dfa-9824-448c-9c93-4743ffb48692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>08556a43-5c1e-4ea6-89b2-16f6ea1c2248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = 'up' and (text() = '2 M' or . = '2 M')]</value>
      <webElementGuid>ff2bb9f6-1018-4450-9632-cfa35526747c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
