<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_OpenCalender</name>
   <tag></tag>
   <elementGuidId>4f26f5ae-17aa-4329-920c-a83db4d8eb64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon-profile_calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wgtbandar']/div/div[2]/form/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25b9565d-89cf-475a-ba81-e2b1295c875a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-profile_calendar</value>
      <webElementGuid>af727547-59dd-411b-9b95-8a7faf10a2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wgtbandar&quot;)/div[@class=&quot;widgetboxin widgetbandar&quot;]/div[@class=&quot;bandar-head&quot;]/form[1]/div[@class=&quot;metric metric-search-symbol&quot;]/a[@class=&quot;icon-profile_calendar&quot;]</value>
      <webElementGuid>16324c87-70c1-4fd3-8ecd-89a7424db730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wgtbandar']/div/div[2]/form/div/a</value>
      <webElementGuid>374434cc-a6f7-48cc-9523-b0488b531940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>32cf8b0c-919a-41e0-9257-2e544283a34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
