<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_BuyerVol2</name>
   <tag></tag>
   <elementGuidId>0a764df9-5d40-4cc2-b980-bf9f9fdb35b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[3]/td[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sc-crXcEl.styled__Td-sc-wb8gs0-1.ibdGcM.GqUtV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fb578cc5-01b1-4e39-b166-6dfeb2fd2ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>90891193-f102-424d-9de3-c07bde1a81db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>38991b5a-9f77-4f30-9806-c4cd51236b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>41154b64-91b0-4bff-b7ad-3b5463b3c6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>9ac7ac30-f761-46e5-a192-0c97cd674c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>padding</name>
      <type>Main</type>
      <value>6px</value>
      <webElementGuid>2ce657a4-41a8-4bdf-8862-43c435d2d8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>family</name>
      <type>Main</type>
      <value>regular</value>
      <webElementGuid>34311a0a-14bd-4390-8e88-acc9bb3944f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>9abd58e9-5a1c-4240-a99d-6335070b7ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-crXcEl styled__Td-sc-wb8gs0-1 ibdGcM GqUtV</value>
      <webElementGuid>33f8d42f-377f-498e-9f40-65d17e03244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minwidth</name>
      <type>Main</type>
      <value>40px</value>
      <webElementGuid>69e6028b-faad-4fc8-b4df-03e5782bcb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 M</value>
      <webElementGuid>d03e0e1a-6313-45b5-ac3e-7c7a815c6e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-BROKER_SUMMARY&quot;)/div[@class=&quot;ant-table-wrapper sc-ehMyHa styled__TableListTransaction-sc-wb8gs0-14 eThjKr kcEcRq&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-ping-right ant-table-fixed-header ant-table-scroll-horizontal&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-body&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/p[@class=&quot;sc-crXcEl styled__Td-sc-wb8gs0-1 ibdGcM GqUtV&quot;]</value>
      <webElementGuid>e9793f6f-27e1-4b41-a82b-45f5a0be8aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@type='up']</value>
      <webElementGuid>65e37f81-6d78-4e12-b012-d8ba67687360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-BROKER_SUMMARY']/div[2]/div/div/div/div/div[2]/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>4ce52506-1ee5-4917-b270-225504bd9b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net'])[1]/following::p[51]</value>
      <webElementGuid>b265bd2a-c206-4f16-935a-b45b0a2b3d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular'])[1]/following::p[51]</value>
      <webElementGuid>f2f2572c-f5ff-433f-b654-059d7c3e6446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATO'])[1]/preceding::p[89]</value>
      <webElementGuid>2e65a89c-ecdc-4ca1-88bc-2a8869dca9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surya Permata Andalan Tbk.'])[1]/preceding::p[89]</value>
      <webElementGuid>7b427ec2-4ec5-4847-aa7a-78bec2ae47b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2 M']/parent::*</value>
      <webElementGuid>b5c5f7b4-557f-4a0d-87a1-834c292aa154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>9cae1ae2-1649-4695-b1be-2edb5a6ffe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = 'up' and (text() = '2 M' or . = '2 M')]</value>
      <webElementGuid>6725b298-1a3e-4771-a063-a89bc7628aaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
