<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_Seller2</name>
   <tag></tag>
   <elementGuidId>0da09619-b996-4f75-8df4-b6f7eed02401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.broker.brokerlist.broker_AZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[3]/td[5]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>25cfb543-aa97-4785-aa61-58226f933bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>broker brokerlist broker_AZ</value>
      <webElementGuid>0be501e5-18eb-4324-a060-c1c29dc8b8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AZ</value>
      <webElementGuid>c31f0a53-60b2-403d-b1a6-6b4ef874ec9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wgtbandar&quot;)/div[@class=&quot;widgetboxin widgetbandar&quot;]/div[@class=&quot;widget-content bandar-content&quot;]/div[1]/table[@class=&quot;brokersum-sell&quot;]/tbody[1]/tr[1]/td[@class=&quot;broker brokerlist broker_AZ&quot;]</value>
      <webElementGuid>d950bcda-2533-4aae-8ded-8e76ec4186e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wgtbandar']/div/div[3]/div/table[2]/tbody/tr/td</value>
      <webElementGuid>73b495db-8b7e-4436-a44c-fd442c5668d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.avg'])[1]/following::td[1]</value>
      <webElementGuid>22646f2c-6fd7-40ec-b1df-1dc43552dd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.val'])[1]/following::td[2]</value>
      <webElementGuid>fa672ad6-a15c-4181-b1d4-3a68a4a70d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MG'])[1]/preceding::td[3]</value>
      <webElementGuid>794f5e4f-bfac-4dfb-b4f6-cd348b159113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EP'])[1]/preceding::td[6]</value>
      <webElementGuid>4119ff81-9bae-4abf-9678-58eb556e61b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AZ']/parent::*</value>
      <webElementGuid>f811784f-00fb-466f-80f0-ff79edf961d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table[2]/tbody/tr/td</value>
      <webElementGuid>c383c48a-510f-401f-9ba7-dc64841a0d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AZ' or . = 'AZ')]</value>
      <webElementGuid>60a5059b-0296-4b21-a1e0-9e4b1e72a824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
