<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_SellerVal3</name>
   <tag></tag>
   <elementGuidId>625d0033-ee9d-4088-bf0e-660a5fdb0f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.broker-sell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div/div[2]/div/div/div/div/div[2]/table/tbody/tr[4]/td[7]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1803ebc6-35a2-4f1f-af92-e44b9cce3cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>broker-sell</value>
      <webElementGuid>2fa2a2a7-f202-4c86-b8fc-be680392c0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-2.9 B</value>
      <webElementGuid>895fec7f-f179-4971-95ee-37c619d96431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wgtbandar&quot;)/div[@class=&quot;widgetboxin widgetbandar&quot;]/div[@class=&quot;widget-content bandar-content&quot;]/div[1]/table[@class=&quot;brokersum-sell&quot;]/tbody[1]/tr[1]/td[@class=&quot;broker-sell&quot;]</value>
      <webElementGuid>1214736e-bf72-4307-b0c1-156a903efd11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wgtbandar']/div/div[3]/div/table[2]/tbody/tr/td[2]</value>
      <webElementGuid>901dd1cf-6806-4b9a-9ec9-c7646bbebaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AZ'])[1]/following::td[1]</value>
      <webElementGuid>2f21a772-b6f3-4162-9d1c-ee41c4a74654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.avg'])[1]/following::td[2]</value>
      <webElementGuid>f9526f33-0fbb-4942-9997-57a76336761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MG'])[1]/preceding::td[2]</value>
      <webElementGuid>3bd48429-a96f-4b8a-aa30-32dc4c95f112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EP'])[1]/preceding::td[5]</value>
      <webElementGuid>67a7efcd-7e38-498e-a257-1e1a54efa603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-2.9 B']/parent::*</value>
      <webElementGuid>dd912c8e-763e-41f4-9682-c033e627208f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table[2]/tbody/tr/td[2]</value>
      <webElementGuid>920d0d2b-0165-4caa-917b-ee4135424ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '-2.9 B' or . = '-2.9 B')]</value>
      <webElementGuid>c89baec8-d522-474a-8539-6a6446b8003c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
