<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_BuyerVol1</name>
   <tag></tag>
   <elementGuidId>e0fda633-3512-4006-8dc1-e2cc0b0541f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[2]/td[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sc-crXcEl.styled__Td-sc-wb8gs0-1.ibdGcM.GqUtV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9fbef471-a135-470a-b4f4-63f0e14e83cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>0c34f493-7481-41e0-ac44-d2778a2913b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>af48e351-b78b-4bf1-b720-80c9f70371b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>cb490344-d110-4417-9c3a-f596b5b7670a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>9e868814-cb5f-45a1-9318-1fb338427084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>padding</name>
      <type>Main</type>
      <value>6px</value>
      <webElementGuid>2aed54d7-2a1e-4c27-ad1a-a8804e7af092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>family</name>
      <type>Main</type>
      <value>regular</value>
      <webElementGuid>4c763815-8cfb-4653-bd83-5a42bb5ccc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>23dacd08-b88d-410e-901b-31ff2ac8df81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-crXcEl styled__Td-sc-wb8gs0-1 ibdGcM GqUtV</value>
      <webElementGuid>f5b57ca4-c241-4f90-ac7b-a44e2f4eb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minwidth</name>
      <type>Main</type>
      <value>40px</value>
      <webElementGuid>0469ff8c-3138-4bc3-9b6f-5798c363a479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 M</value>
      <webElementGuid>4f4bcb3c-5968-4783-9bcf-4a5a89e8cbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-BROKER_SUMMARY&quot;)/div[@class=&quot;ant-table-wrapper sc-ehMyHa styled__TableListTransaction-sc-wb8gs0-14 eThjKr kcEcRq&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-ping-right ant-table-fixed-header ant-table-scroll-horizontal&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-body&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/p[@class=&quot;sc-crXcEl styled__Td-sc-wb8gs0-1 ibdGcM GqUtV&quot;]</value>
      <webElementGuid>992bb7de-61c0-4b6b-a177-c30b46113a89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@type='up']</value>
      <webElementGuid>2638d1fc-532a-40ff-8e4a-bfec431ade9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-BROKER_SUMMARY']/div[2]/div/div/div/div/div[2]/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>86976059-781e-4bee-8282-78ad754ea544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net'])[1]/following::p[51]</value>
      <webElementGuid>21299335-4d22-4659-9765-75b67a2ac20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular'])[1]/following::p[51]</value>
      <webElementGuid>d26ebe44-58fe-48f1-a15f-993f6b5ee006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATO'])[1]/preceding::p[89]</value>
      <webElementGuid>cbe48aad-2a50-4cad-bf55-de956d4461b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surya Permata Andalan Tbk.'])[1]/preceding::p[89]</value>
      <webElementGuid>65c22c13-2d85-4f0a-aec3-028c0b08761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2 M']/parent::*</value>
      <webElementGuid>0e29bdc2-1cd6-47ca-a080-cecfd9d3a3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/p</value>
      <webElementGuid>14f659b7-44f8-4dad-85af-84e5b77f9f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = 'up' and (text() = '2 M' or . = '2 M')]</value>
      <webElementGuid>17d052d8-2856-4dbf-9afa-6194b764ea58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
