<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_SellerVal2</name>
   <tag></tag>
   <elementGuidId>046dd0e4-bbbc-4a75-819e-7f8aca18d26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.broker-sell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[3]/td[7]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a0b08afe-ba1d-4d96-9ee8-7d5730db5028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>broker-sell</value>
      <webElementGuid>91b7a6c6-417c-4827-b84b-7427d619824c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-2.9 B</value>
      <webElementGuid>2f3de087-8bb6-4209-a5b3-1c525678fe00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wgtbandar&quot;)/div[@class=&quot;widgetboxin widgetbandar&quot;]/div[@class=&quot;widget-content bandar-content&quot;]/div[1]/table[@class=&quot;brokersum-sell&quot;]/tbody[1]/tr[1]/td[@class=&quot;broker-sell&quot;]</value>
      <webElementGuid>60e7d4cd-7fe9-4a24-ad3e-97044c34b265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wgtbandar']/div/div[3]/div/table[2]/tbody/tr/td[2]</value>
      <webElementGuid>3d9f6381-ddba-4f0c-aa0c-6392ae29ff5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AZ'])[1]/following::td[1]</value>
      <webElementGuid>b3c96f25-9ddb-4fe3-9746-2335ee5856d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.avg'])[1]/following::td[2]</value>
      <webElementGuid>2b3fca08-4212-476b-b670-25309fa180f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MG'])[1]/preceding::td[2]</value>
      <webElementGuid>b7c81159-13dd-4856-a082-74d9efcea0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EP'])[1]/preceding::td[5]</value>
      <webElementGuid>875b8d57-d5be-4da5-9213-8cccd671786d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-2.9 B']/parent::*</value>
      <webElementGuid>b90d78de-b317-4103-b8c6-89e9907fe925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table[2]/tbody/tr/td[2]</value>
      <webElementGuid>31970d74-78a3-4a2b-855c-01917a072034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '-2.9 B' or . = '-2.9 B')]</value>
      <webElementGuid>e2b94491-6d4f-4acc-b9f4-c97991dfe29d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
