<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bandarmology_Seller3</name>
   <tag></tag>
   <elementGuidId>7e344768-a718-4440-b42c-1cc2771d645e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.broker.brokerlist.broker_AZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'rc-tabs-')]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[5]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b9ce9140-eddc-4462-a0e6-c8e94e440cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>broker brokerlist broker_AZ</value>
      <webElementGuid>0e974ea1-18e3-4afc-b63c-417d1d45a21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AZ</value>
      <webElementGuid>dec43abe-95db-4681-8541-d545ec46ddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wgtbandar&quot;)/div[@class=&quot;widgetboxin widgetbandar&quot;]/div[@class=&quot;widget-content bandar-content&quot;]/div[1]/table[@class=&quot;brokersum-sell&quot;]/tbody[1]/tr[1]/td[@class=&quot;broker brokerlist broker_AZ&quot;]</value>
      <webElementGuid>e831489c-b9f0-497a-80e5-339df9cb15f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wgtbandar']/div/div[3]/div/table[2]/tbody/tr/td</value>
      <webElementGuid>81c5bcfd-6246-47bf-b5b2-12774b5988d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.avg'])[1]/following::td[1]</value>
      <webElementGuid>80b2b3c1-6d0d-4763-bf7f-28ebd09c7338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S.val'])[1]/following::td[2]</value>
      <webElementGuid>f9d1580d-efee-48a4-83b2-ac1370413535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MG'])[1]/preceding::td[3]</value>
      <webElementGuid>da3468ef-7c6a-4d93-b778-7d3f7e64eb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EP'])[1]/preceding::td[6]</value>
      <webElementGuid>7b4be5e3-303a-44de-8c5a-648267c62014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AZ']/parent::*</value>
      <webElementGuid>cc65dcac-d7ff-4969-963f-6d4da4caf3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table[2]/tbody/tr/td</value>
      <webElementGuid>d88f49d5-b6ae-48b6-820a-aca67f35adcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AZ' or . = 'AZ')]</value>
      <webElementGuid>d3acdf98-9f23-47f5-a7de-6be4d243efb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
