<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home_LowPrice</name>
   <tag></tag>
   <elementGuidId>008051d2-627e-462b-93d6-a0062c692b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.AVIA-LIVE-LOW.info-low.ordrbook-arrow-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div[4]/div[2]/div/table/tbody/tr[3]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ddbffa2c-519a-4624-a3bf-8ff619fc313b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AVIA-LIVE-LOW info-low ordrbook-arrow-down</value>
      <webElementGuid>b8f70607-0c41-403b-9d0e-2bdd0962a947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>9a94dd6e-8c43-4c13-b886-80c7d1bbc9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ordrbook-wrapper&quot;)/div[@class=&quot;ordrbook-item-info&quot;]/table[1]/tbody[1]/tr[3]/td[@class=&quot;AVIA-LIVE-LOW info-low ordrbook-arrow-down&quot;]</value>
      <webElementGuid>67df715f-a718-4ba5-b91f-5e307dc83022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ordrbook-wrapper']/div[2]/table/tbody/tr[3]/td[4]</value>
      <webElementGuid>b679b9ab-6629-4b7a-a6f6-e90866c64e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/following::td[1]</value>
      <webElementGuid>462b05c7-4315-4fb1-b586-7dac1fd12e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::td[3]</value>
      <webElementGuid>948f5f5a-fc68-4d05-99cd-0f179dc08c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avg'])[1]/preceding::td[1]</value>
      <webElementGuid>c4919df8-c08e-4ca5-b621-d2b8ff29ea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lot'])[2]/preceding::td[3]</value>
      <webElementGuid>471de797-3a6f-444b-9723-f635f04a6df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]</value>
      <webElementGuid>11deed4a-68a1-439a-b1cd-c16ea7bb5dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '700' or . = '700')]</value>
      <webElementGuid>f6bf5a3b-ceca-4ace-af84-05c8ecd58df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
