<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home_Freq</name>
   <tag></tag>
   <elementGuidId>6ee1d9a2-cd6e-4b07-9674-4299575dfb17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div[4]/div[2]/div/table/tbody/tr[4]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>60ef7dbc-a3ff-4692-981c-11ce4b2f0ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>284</value>
      <webElementGuid>080a2f42-e54b-4212-84d1-0c2f30f23c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;sc-gKXOVf jDwjYN&quot;]/div[@class=&quot;sc-38e19fcd-2 haGIBC&quot;]/div[@class=&quot;sc-eb5a766a-13 dAeJvp&quot;]/table[@class=&quot;table-live-price&quot;]/tbody[1]/tr[4]/td[2]</value>
      <webElementGuid>ac285a49-248b-433d-a57e-8c1e0bba1a20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[4]/div[2]/div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>5ba66ab2-9106-4f92-9e87-b2c653665a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freq'])[1]/following::td[1]</value>
      <webElementGuid>7c2a4b23-d7e1-4c8e-803a-8109a9ae39a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avg'])[1]/following::td[3]</value>
      <webElementGuid>c9c8633c-cd42-455c-8879-4821e99c0f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F Buy'])[1]/preceding::td[1]</value>
      <webElementGuid>b1fd716b-39dc-44cf-a0bb-fa59037bddea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F Sell'])[1]/preceding::td[3]</value>
      <webElementGuid>2250699e-b7d6-429d-9f31-3db328a54251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='284']/parent::*</value>
      <webElementGuid>e24acacf-a6d3-43bc-9279-280e1bd2576f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>d4981e26-4e83-46c8-a30c-9d43f5bfdca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '284' or . = '284')]</value>
      <webElementGuid>3bacbed6-1c13-480c-8216-1267f579b5aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
