<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home_AVGPrice</name>
   <tag></tag>
   <elementGuidId>a13b490a-b2f8-44cf-b55e-9d493ccca48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div[4]/div[2]/div/table/tbody/tr[3]/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d7fb8fc6-e649-4d00-a55f-cc47e0f9a6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>836e9c48-b0c1-48ea-aa33-ca044e3ed2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>187</value>
      <webElementGuid>69bf0504-2148-400c-97d8-3f0d1c860a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;sc-gKXOVf jDwjYN&quot;]/div[@class=&quot;sc-38e19fcd-2 haGIBC&quot;]/div[@class=&quot;sc-eb5a766a-13 dAeJvp&quot;]/table[@class=&quot;table-live-price&quot;]/tbody[1]/tr[3]/td[@class=&quot;up&quot;]</value>
      <webElementGuid>2676e8f1-36af-4449-afce-7dee4c81a5e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[4]/div[2]/div/table/tbody/tr[3]/td[6]</value>
      <webElementGuid>41c197fe-04a8-4f56-ae02-d205a2025372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avg'])[1]/following::td[1]</value>
      <webElementGuid>6e2a9016-1dba-411a-8024-1f15b5cb1f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/following::td[3]</value>
      <webElementGuid>2298688e-7349-4965-8354-f05881e8a316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lot'])[2]/preceding::td[1]</value>
      <webElementGuid>87083e2b-8905-4a9b-9a0e-b522aee8fccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bid'])[1]/preceding::td[1]</value>
      <webElementGuid>6d457c1e-544c-4262-af4d-730c79067879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='187']/parent::*</value>
      <webElementGuid>4ea62dda-8947-4a13-83a6-c19c6fbcb93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]</value>
      <webElementGuid>d6fc8dca-5e72-49c1-b22a-27577a69f6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '187' or . = '187')]</value>
      <webElementGuid>b6df7637-cd15-448c-a7ba-a61d5fb056ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
