<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__Profile</name>
   <tag></tag>
   <elementGuidId>ef91f3c2-4a7f-416c-a5bf-ab880524f88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.popavatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stockbit-header-web']/div/div/div[2]/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78d26dd1-5fbf-40f6-bec1-e37eb2fe68c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popavatar</value>
      <webElementGuid>2ab8a250-2e28-4b20-a111-c1b86a9ef2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatar.stockbit.com/placeholders/F.png</value>
      <webElementGuid>6cf9d923-9d86-4f57-8c68-f0223d29f222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-right&quot;)/div[@class=&quot;tabs-menu&quot;]/span[@class=&quot;headermenu user&quot;]/a[@class=&quot;ant-dropdown-link&quot;]/i[1]/img[@class=&quot;popavatar&quot;]</value>
      <webElementGuid>03698732-5763-490b-824c-9d5f30a11023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-right']/div[2]/span/a/i/img</value>
      <webElementGuid>35e3f9e2-d382-434a-9d2c-81a8a8c5dacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://avatar.stockbit.com/placeholders/F.png')]</value>
      <webElementGuid>36c3ad47-1a48-4352-a794-dcbef4b9203b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/img</value>
      <webElementGuid>449bb0a6-2828-4050-b26a-d7b5ddbafc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://avatar.stockbit.com/placeholders/F.png']</value>
      <webElementGuid>ce397206-d06d-4398-b2f0-c055d166bc59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
