<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LotBid_1</name>
   <tag></tag>
   <elementGuidId>aa2b804e-2748-498b-87cd-c0b00c5f69f6</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ordrbook-wrapper']/div[3]/table/tbody/tr[1]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1414de63-2780-4181-b227-72344a17f25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9,107</value>
      <webElementGuid>be4a12f6-4ee2-4b4b-9f1a-26cee4285076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ordrbook-wrapper&quot;)/div[@class=&quot;CHEM-LIVE-ITEMLIST ordrbook-item-list&quot;]/table[1]/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>05ed4649-5510-4b9e-8efa-e8ded980b17f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ordrbook-wrapper']/div[3]/table/tbody/tr/td[2]</value>
      <webElementGuid>f5c810a9-dadf-446d-a9b7-e3d5b807b059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lot'])[3]/following::td[2]</value>
      <webElementGuid>0c72cd62-1456-408a-8acd-5d2af8079603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offer'])[1]/following::td[2]</value>
      <webElementGuid>81bd0e29-2905-47fc-9e84-71ee995b72d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/preceding::td[61]</value>
      <webElementGuid>9a94d6e0-9915-41fe-9d2a-ba560b5670ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Running Trade'])[1]/preceding::td[64]</value>
      <webElementGuid>7fab7dbc-e87e-43fc-9638-a89a84c1afb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9,107']/parent::*</value>
      <webElementGuid>218b434b-b06b-4654-b56e-69fdb25a791b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]</value>
      <webElementGuid>6ef71788-c7dd-49f8-856c-66e0dbdda256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '9,107' or . = '9,107')]</value>
      <webElementGuid>a360a65b-9c06-4357-8353-ebb84393c0ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
