<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Bandarmology</name>
   <tag></tag>
   <elementGuidId>33951da9-a64f-4ab6-81f5-0d23bf548f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/button[6]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.wbandar.icon-widget_bandar.ant-tooltip-open</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d696dfb0-eec9-48a2-8624-fb00b4dd3671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wbandar icon-widget_bandar ant-tooltip-open</value>
      <webElementGuid>d9468464-a0e1-44cf-90a0-d25fab281738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>bandar</value>
      <webElementGuid>1ce220f0-2614-4803-ae0a-2cf3023aaa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-action</name>
      <type>Main</type>
      <value>bandar_detector</value>
      <webElementGuid>4822b3eb-3b8e-4b25-b3af-9b0ea8d21327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightmenu&quot;)/a[@class=&quot;wbandar rightmenu-anchor&quot;]/i[@class=&quot;wbandar icon-widget_bandar ant-tooltip-open&quot;]</value>
      <webElementGuid>feb96f95-2cf6-4f60-91c2-eef5d0f9e08c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightmenu']/a[7]/i</value>
      <webElementGuid>ac72dbe4-a449-4aff-8462-418760f80479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]/i</value>
      <webElementGuid>28885213-c091-4486-89eb-016cbfc1d1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
