<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>screener_Midatomi</name>
   <tag></tag>
   <elementGuidId>029bfa8e-303c-41eb-8f93-8c191a8bc5b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'sc-crXcEl dwOlnB' and (text() = 'Midatomi' or . = 'Midatomi')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='WEHA'])[1]/following::p[95]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>632a478b-f4af-4616-8fb4-73fa02219ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>calc(100% - 48px)</value>
      <webElementGuid>8f80e6df-00c4-484c-92b7-ca168f42c11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>6562b2b3-a817-4d5c-83dd-1ca17679d1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>72b8dc52-ed97-498b-99c5-b2638d951030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>68433487-0dab-4ac4-975e-c649a5600fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>ba5df0fa-205e-464c-925e-88b12ebbfca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>padding</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d1b575e-66bc-48fd-b9f2-b37602e97ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>family</name>
      <type>Main</type>
      <value>regular</value>
      <webElementGuid>dceba7f2-3c46-4b04-b3a3-30e33e9936d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-crXcEl dwOlnB</value>
      <webElementGuid>0d62168a-cab8-4059-8714-eeb5b22869a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Midatomi</value>
      <webElementGuid>7829952b-b972-443b-9df3-7490e0855acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[1]/div[@class=&quot;ant-popover ant-popover-placement-bottomRight&quot;]/div[@class=&quot;ant-popover-content&quot;]/div[@class=&quot;ant-popover-inner&quot;]/div[@class=&quot;ant-popover-inner-content&quot;]/div[@class=&quot;sc-fEOsli FavoritesDropdown__ContentWrapper-sc-l4wsbb-0 cMXIKI frwBmb&quot;]/div[@class=&quot;sc-gKXOVf FavoritesDropdown__SFlexItemFavoriteContainer-sc-l4wsbb-1 SHKyB kOMXRm&quot;]/div[@class=&quot;sc-gKXOVf FavoritesDropdown__SFlexItemFavorite-sc-l4wsbb-2 jvpZFd fgkGta&quot;]/p[@class=&quot;sc-crXcEl dwOlnB&quot;]</value>
      <webElementGuid>8d1ca5a2-429d-43ff-9f92-1a7d24af54af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEHA'])[1]/following::p[95]</value>
      <webElementGuid>63ac8444-9352-41f8-af79-123983b599d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SINI'])[1]/following::p[95]</value>
      <webElementGuid>d5c145f7-d89f-4067-b308-9aa2a527029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watchlist'])[4]/preceding::p[15]</value>
      <webElementGuid>3663b19b-05e3-4707-93c5-b45d59e8f63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::p[15]</value>
      <webElementGuid>f4249c28-8993-4415-8bd6-b2b97d507a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Midatomi']/parent::*</value>
      <webElementGuid>9d9bfd22-5124-4748-889f-187ac92be595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/p</value>
      <webElementGuid>9c5986a7-491f-443f-831d-582f786a334e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Midatomi' or . = 'Midatomi')]</value>
      <webElementGuid>e50008c0-ef7b-4f78-bd78-3e8eec29fcaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
