<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>screener_Favorites</name>
   <tag></tag>
   <elementGuidId>afc48f51-d213-4c07-a967-453e214cc7c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div[2]/div/div[2]/button/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.screener-more</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c0a93f0-d94a-4407-8f5e-77f0df123703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>screener-more</value>
      <webElementGuid>c34322e9-b3db-4781-941e-ec82a6786041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>aeb894a4-b7f7-468a-8938-a39b5cab9e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genhead&quot;)/div[2]/div[@class=&quot;screener-menu-box&quot;]/table[1]/tbody[1]/tr[1]/td[2]/span[@class=&quot;screener-more&quot;]</value>
      <webElementGuid>3b6792ff-be85-42b7-8629-42b2a039adef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='genhead']/div[2]/div[2]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>0d331faf-111f-4fb7-baad-c85bfc06b77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trend Following Iseng'])[1]/following::span[1]</value>
      <webElementGuid>e5c37b03-9b89-4ff7-96b1-27ce9d8b0bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vol + Accum + MA5 + PER&lt;20'])[1]/following::span[2]</value>
      <webElementGuid>d1f3693e-2705-40d5-ab4d-0f3067c42e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Screener'])[1]/preceding::span[1]</value>
      <webElementGuid>83fe59db-2b6f-42bd-aa57-11f7a92be72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Screen Name'])[1]/preceding::span[1]</value>
      <webElementGuid>10ba2233-cedd-4e51-a9d1-7039662f3006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Favorites']/parent::*</value>
      <webElementGuid>dfcc9880-4f19-46bc-bb92-6c15747e316c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>4279eca3-c7a0-4297-ad04-9662a86d2ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>b8c86fc4-7db0-4081-b620-f9cec3a6413b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
