<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>26c6107d-361e-4567-942b-44162b8c548d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='screener-result']/div[2]/div[2]/div/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.symbol-title.headcol.sr2</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>28a5cca6-d12c-49bd-aa31-55f97bca0878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbol-title headcol sr2</value>
      <webElementGuid>0a8a9ad9-9b51-4627-a13e-9772e723db92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-raw</name>
      <type>Main</type>
      <value>MRAT</value>
      <webElementGuid>921f0a04-2679-4404-bb7e-f13334666925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MRAT</value>
      <webElementGuid>3c40888d-a9f2-4ff0-b72f-e7650f1dbc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;screener-result&quot;)/div[@class=&quot;general-content-in&quot;]/div[@class=&quot;wrap-outer&quot;]/div[@class=&quot;wrap-inner&quot;]/table[@class=&quot;wl-table screener-table&quot;]/tbody[1]/tr[1]/td[@class=&quot;symbol-title headcol sr2&quot;]</value>
      <webElementGuid>dae97028-a4f8-415d-ba5f-ec77c1f49acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='screener-result']/div[2]/div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>b9dbd453-b270-4349-8178-68d87faa529c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='❌'])[7]/following::td[1]</value>
      <webElementGuid>71dfad33-171f-428f-be4c-91e6a6a74889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bandar Accum/Dist'])[1]/following::td[1]</value>
      <webElementGuid>8730803d-a38d-46d4-8d7c-8a5468da9d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KRYA'])[1]/preceding::td[8]</value>
      <webElementGuid>71123de9-bc8e-40d2-86a6-45b91582b64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>0fcdac30-80d7-4d9e-87ec-600aa723e285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'MRAT' or . = 'MRAT')]</value>
      <webElementGuid>f547c4f2-bc10-49da-9ac7-0b4048db83d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
