<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Result2</name>
   <tag></tag>
   <elementGuidId>fe8d49aa-261d-40b0-b61d-db050eac0514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='screener-result']/div[2]/div[2]/div/table/tbody/tr[2]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9edc1d54-6ceb-460f-84e8-8424a4b1bb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbol-title headcol sr2</value>
      <webElementGuid>5f2636b3-8c24-4427-8e86-8e8bfd0a2eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-raw</name>
      <type>Main</type>
      <value>KOBX</value>
      <webElementGuid>5e081fbc-4bb0-4048-8112-7d87242037b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOBX</value>
      <webElementGuid>20bd2959-e950-44f3-834c-e04aa2647302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;screener-result&quot;)/div[@class=&quot;general-content-in&quot;]/div[@class=&quot;wrap-outer&quot;]/div[@class=&quot;wrap-inner&quot;]/table[@class=&quot;wl-table screener-table&quot;]/tbody[1]/tr[6]/td[@class=&quot;symbol-title headcol sr2&quot;]</value>
      <webElementGuid>c13a311f-bd3d-4554-913c-db1f6fc80043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='screener-result']/div[2]/div[2]/div/table/tbody/tr[6]/td</value>
      <webElementGuid>d8ece563-3b60-4c12-a571-62a13e765d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRJA'])[1]/following::td[8]</value>
      <webElementGuid>3d271841-e655-4c6a-ab61-37a5db25cec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BNBR'])[1]/following::td[16]</value>
      <webElementGuid>367d0fbd-90c4-4200-98fa-2de9cccdc85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GDST'])[1]/preceding::td[8]</value>
      <webElementGuid>d90d22e7-4e8c-4da3-86be-a09f0220277f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[1]</value>
      <webElementGuid>38803ca4-a550-4c88-98a3-58d520facecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>255482f4-2fce-4e49-8e7a-050cf5c83a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
